name: cicd
on:
  push:
    branches: ['master']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_IMAGE_NAME }}
          build-args:
            db_host: ${{ secrets.DB_HOST }}
            db_name: ${{ secrets.DB_NAME }}
            db_user: ${{ secrets.DB_USERNAME }}
            db_password: ${{ secrets.DB_PASSWORD }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOSTS }}
          username: root
          password: ${{ secrets.REMOTE_SSH_PASSWORD }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_IMAGE_NAME }}
            docker stop $${{ secrets.DOCKER_IMAGE_NAME }} || true && docker rm $${{ secrets.DOCKER_IMAGE_NAME }} || true
            docker run -d -p 3000:9090 ${{ secrets.DOCKER_IMAGE_NAME }} --name $${{ secrets.DOCKER_IMAGE_NAME }}
            docker image prune -a -f